version: '2'
services:
  cuberite:
    image: lacquerlabs/cuberite:latest
    environment:
      - PORT=25565
    ports:
      - "25565:25565"
      - "8080:8080"
    volumes:
      - volume_cuberite:/app

volumes:
  volume_cuberite:

